### ISSUE TITLE
Brugerzoom clasher med zoom af kort

### ISSUE THREAD

**Issue by PelleSwelle** [Dataforsyningen/Koordinattransformation#24]
Zoom på kortet er fint og dejligt, men hvis man zoomer, mens man er henover nålen eller inden for Card'et zoomer hele siden, og det skal den ikke.

**Comment by david-vinje** [comment]
Det lader til at virke på telefon - jeg tror ikke, det er ikke muligt at fjerne 100 % fra browseren.
